// export const formFields = [
//     { name: 'profilePicture', label: 'Profile Picture', type: 'file' },
//     { name: 'email', label: 'Email', type: 'email' },
//     { name: 'name', label: 'Name', type: 'text' },
//     { name: 'address', label: 'Address', type: 'text' },
//     { name: 'state', label: 'State', type: 'text' },
//     { name: 'mobile', label: 'Mobile No', type: 'tel' },
//     { name: 'zipcode', label: 'Zipcode', type: 'text' },
//   ];
  
//   import Flags from 'country-flag-icons/react/3x2'


// export const countries = [
//   { code: 'US', name: 'United States', flag: Flags.US },
//   { code: 'GB', name: 'United Kingdom', flag: Flags.GB },
//   { code: 'CA', name: 'Canada', flag: Flags.CA },
//   { code: 'AU', name: 'Australia', flag: Flags.AU },
//   { code: 'DE', name: 'Germany', flag: Flags.DE },
//   { code: 'FR', name: 'France', flag: Flags.FR },
//   { code: 'JP', name: 'Japan', flag: Flags.JP },
//   { code: 'CN', name: 'China', flag: Flags.CN },
//   { code: 'IN', name: 'India', flag: Flags.IN },
//   { code: 'BR', name: 'Brazil', flag: Flags.BR },
//   // Add more countries as needed
// ]
// export const states = [
//     { value: 'AL', label: 'Alabama' },
//     { value: 'AK', label: 'Alaska' },
//     { value: 'AZ', label: 'Arizona' },
//     { value: 'AR', label: 'Arkansas' },
//     { value: 'CA', label: 'California' },
//     { value: 'CO', label: 'Colorado' },
//     { value: 'CT', label: 'Connecticut' },
//     { value: 'DE', label: 'Delaware' },
//     { value: 'FL', label: 'Florida' },
//     { value: 'GA', label: 'Georgia' },
//     { value: 'HI', label: 'Hawaii' },
//     { value: 'ID', label: 'Idaho' },
//     { value: 'IL', label: 'Illinois' },
//     { value: 'IN', label: 'Indiana' },
//     { value: 'IA', label: 'Iowa' },
//     { value: 'KS', label: 'Kansas' },
//     { value: 'KY', label: 'Kentucky' },
//     { value: 'LA', label: 'Louisiana' },
//     { value: 'ME', label: 'Maine' },
//     { value: 'MD', label: 'Maryland' },
//     { value: 'MA', label: 'Massachusetts' },
//     { value: 'MI', label: 'Michigan' },
//     { value: 'MN', label: 'Minnesota' },
//     { value: 'MS', label: 'Mississippi' },
//     { value: 'MO', label: 'Missouri' },
//     { value: 'MT', label: 'Montana' },
//     { value: 'NE', label: 'Nebraska' },
//     { value: 'NV', label: 'Nevada' },
//     { value: 'NH', label: 'New Hampshire' },
//     { value: 'NJ', label: 'New Jersey' },
//     { value: 'NM', label: 'New Mexico' },
//     { value: 'NY', label: 'New York' },
//     { value: 'NC', label: 'North Carolina' },
//     { value: 'ND', label: 'North Dakota' },
//     { value: 'OH', label: 'Ohio' },
//     { value: 'OK', label: 'Oklahoma' },
//     { value: 'OR', label: 'Oregon' },
//     { value: 'PA', label: 'Pennsylvania' },
//     { value: 'RI', label: 'Rhode Island' },
//     { value: 'SC', label: 'South Carolina' },
//     { value: 'SD', label: 'South Dakota' },
//     { value: 'TN', label: 'Tennessee' },
//     { value: 'TX', label: 'Texas' },
//     { value: 'UT', label: 'Utah' },
//     { value: 'VT', label: 'Vermont' },
//     { value: 'VA', label: 'Virginia' },
//     { value: 'WA', label: 'Washington' },
//     { value: 'WV', label: 'West Virginia' },
//     { value: 'WI', label: 'Wisconsin' },
//     { value: 'WY', label: 'Wyoming' }
//   ];
  
  